### ISSUE TITLE
Lot number, Expiry Date

### ISSUE THREAD

**Issue by mrdlaaziz** [ajepe/pos_customization#3]
![2](https://user-images.githubusercontent.com/91767192/215333184-d0cffa1f-4032-4d48-80ed-7969a8c0ffa9.JPG)
Expiry date / Lot Number are not recorded in the backend

**Comment by ajepe** [comment]
Do  you want the lot number to be created automatically? because currently when lot number is entered. I search the back-end for the available lot number.

**Comment by mrdlaaziz** [comment]
yes, it needs to be created with the entered expiry date on back end as well.

**Comment by ajepe** [comment]
Noted, fixing it now
