### ISSUE TITLE
Missing Orders

### ISSUE THREAD

**Issue by mrdlaaziz** [ajepe/pos_customization#8]
![5](https://user-images.githubusercontent.com/91767192/215335979-6f11513c-ac60-4cc0-b566-45492b6e4f6e.JPG)
Orders are not loading on POS Orders Screen
![6](https://user-images.githubusercontent.com/91767192/215336043-b3d8a8f4-9234-4777-847b-37fcc6aaee4d.JPG)
All working well on back end and invoices are loaded properly as well

**Comment by ajepe** [comment]
how can I replicate this issue?

I created 3 orders from the pos and was able to see the 3 orders both in the backend and frontend. Don't forget that i have filtered our returned orders from the list. i.e a return order will not show in the list of orders.

**Comment by mrdlaaziz** [comment]
we will re-install addons and try again.

**Comment by ajepe** [comment]
Do you have a testing environment where I can also test

**Comment by ajepe** [comment]
Do you have a testing environment where I can also test

**Comment by ajepe** [comment]
Do you have a testing environment where I can also test

**Comment by mrdlaaziz** [comment]
softlink.hopto.org
DB: TEST
admin / admin

**Comment by ajepe** [comment]
Thanks

**Comment by ajepe** [comment]
Good morning, can you give me ssh access to the server also? trying to troubleshoot the missing orders futher

**Comment by mrdlaaziz** [comment]
134.209.232.10
user: root
Pwd: CH19.Grozny

**Comment by ajepe** [comment]
The custom addons are mixed with the odoo base module, that is not the correct way to set it up. I will sort it out and send you the directory for custom addons soon.

**Comment by ajepe** [comment]
Please send me the custom modules
account_testweb_smobile_community
	accounting_pdf_reports
	aspl_website_customer_wallet
	backend_theme_v14
	fims_login_background_and_styles
	hide_menu_user
	hide_powered_by_and_manage_db
	hide_powered_by_odoo
	ks_pos_low_stock_alert
	mpl_pos_multi_lot
	multicolor_backend_theme
	nati_arabic_font
	odoo_dynamic_dashboard
	odoo_dynamic_dashboard_extend
	odoo_web_login
	odoo_whatsapp_integration
	om_account_accountant
	om_account_asset
	om_account_bank_statement_import
	om_account_budget
	om_account_daily_reports
	om_account_followup
	om_credit_limit
	om_recurring_payments
	openeducat_activity
	openeducat_admission
	openeducat_assignment
	openeducat_attendance
	openeducat_classroom
	openeducat_core
	openeducat_exam
	openeducat_facility
	openeducat_fees
	openeducat_library
	openeducat_parent
	openeducat_timetable
	pos_add_product_barcode_no_reload
	pos_all_in_one
	pos_delete_orderline
	pos_fast_loading
	pos_multi_uom_price
	pos_orders_all
	rt_hide_show_password
	sh_pos_keyboard_shortcut
	softlink_pos_low_stock
	theme_paptic
	to_attendance_device
	to_base
	to_safe_confirm_button
	web_openeducat
	web_responsive
	web_smobile_community
	web_window_title
I need to add it to the git repository

**Comment by mrdlaaziz** [comment]
> Please send me the custom modules
> account_testweb_smobile_community
> 	accounting_pdf_reports
> 	aspl_website_customer_wallet
> 	backend_theme_v14
> 	fims_login_background_and_styles
> 	hide_menu_user
> 	hide_powered_by_and_manage_db
> 	hide_powered_by_odoo
> 	ks_pos_low_stock_alert
> 	mpl_pos_multi_lot
> 	multicolor_backend_theme
> 	nati_arabic_font
> 	odoo_dynamic_dashboard
> 	odoo_dynamic_dashboard_extend
> 	odoo_web_login
> 	odoo_whatsapp_integration
> 	om_account_accountant
> 	om_account_asset
> 	om_account_bank_statement_import
> 	om_account_budget
> 	om_account_daily_reports
> 	om_account_followup
> 	om_credit_limit
> 	om_recurring_payments
> 	openeducat_activity
> 	openeducat_admission
> 	openeducat_assignment
> 	openeducat_attendance
> 	openeducat_classroom
> 	openeducat_core
> 	openeducat_exam
> 	openeducat_facility
> 	openeducat_fees
> 	openeducat_library
> 	openeducat_parent
> 	openeducat_timetable
> 	pos_add_product_barcode_no_reload
> 	pos_all_in_one
> 	pos_delete_orderline
> 	pos_fast_loading
> 	pos_multi_uom_price
> 	pos_orders_all
> 	rt_hide_show_password
> 	sh_pos_keyboard_shortcut
> 	softlink_pos_low_stock
> 	theme_paptic
> 	to_attendance_device
> 	to_base
> 	to_safe_confirm_button
> 	web_openeducat
> 	web_responsive
> 	web_smobile_community
> 	web_window_title
> I need to add it to the git repository

Copy any module u need directly from server

**Comment by mrdlaaziz** [comment]
Copy any module u need directly from server
Some modules are not related to the update u are working on, they are rrlated to other customization projects.

**Comment by ajepe** [comment]
All the custom addons needs to be in the same directory, it is  just the standard setup

**Comment by ajepe** [comment]
Let me know if I should do the setup properly. in that wise all the developers will be using working in the same repository

**Comment by mrdlaaziz** [comment]
It is okay, u can use a custom addons folder.
